### ISSUE TITLE
Getting error on running serenity report after changing the feature files folder

### ISSUE THREAD

**Issue by MJavedAli** [abhinaba-ghosh/protractor-cucumber-serenity-typescript-starter#2]
I have moved out the features folders outside the e2e folder . Now on running npm run report I am getting the below exception in console . 

I updated the requirementDirectory folder in config.ts as below - 
serenity: {
    runner: 'cucumber',
    requirementsDirectory: '../features',
    crew: [
      ArtifactArchiver.storingArtifactsAt('./target/site/serenity'),
      new SerenityBDDReporter(),
      ConsoleReporter.withDefaultColourSupport(),
      Photographer.whoWill(TakePhotosOfInteractions),
    ],
  },

EXCEPTION :- 
Exception in thread "main" java.lang.NullPointerException
        at net.thucydides.core.requirements.model.cucumber.CucumberParser.loadCucumberFeatures(CucumberParser.java:106)
        at net.thucydides.core.requirements.model.cucumber.CucumberParser.loadFeature(CucumberParser.java:72)
        at net.thucydides.core.requirements.model.cucumber.CucumberParser.loadFeatureNarrative(CucumberParser.java:136)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.loadFromFeatureFile(FileSystemRequirementsTagProvider.java:624)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.readRequirementsFromStoryOrFeatureFile(FileSystemRequirementsTagProvider.java:573)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider$$Lambda$75/1965445467.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.capabilitiesAndStoriesIn(FileSystemRequirementsTagProvider.java:197)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider$$Lambda$65/1702143276.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.getRequirements(FileSystemRequirementsTagProvider.java:179)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.readChildrenFrom(FileSystemRequirementsTagProvider.java:739)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.requirementFromDirectoryName(FileSystemRequirementsTagProvider.java:648)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.readRequirementFrom(FileSystemRequirementsTagProvider.java:560)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider$$Lambda$70/1908043086.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.capabilitiesAndStoriesIn(FileSystemRequirementsTagProvider.java:193)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider$$Lambda$65/1702143276.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.getRequirements(FileSystemRequirementsTagProvider.java:179)
        at net.thucydides.core.requirements.reports.FileSystemRequirmentsOutcomeFactory.buildRequirementsOutcomesFrom(FileSystemRequirmentsOutcomeFactory.java:52)
        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:154)
        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:136)
        at net.serenitybdd.cli.reporters.CLIAggregateReportGenerator.generateReportsFrom(CLIAggregateReportGenerator.java:66)
        at net.serenitybdd.cli.SerenityCLIReportCoordinator.execute(SerenityCLIReportCoordinator.java:56)
        at net.serenitybdd.cli.Serenity.executeWith(Serenity.java:116)
        at net.serenitybdd.cli.Serenity.main(Serenity.java:80)
I'm terribly sorry, but something didn't go according to plan.
The following process exited with 1: C:/Program Files/Java/jdk1.8.0_25/bin/java.exe -DLOG_LEVEL=warn -Dlogback.configurationFile=C:\Users\vn50ihd\WM_Project\Protractor_Cucumber\GD_CCPA_QA_Automation\node_modules\@serenity-js\serenity-bdd\resources\logback.config.xml -jar lib/serenity-cli/serenity-cli-2.1.10-all.jar --destination target/site/serenity --features features --source
target/site/serenity --project MJCC_QA_Automation

**Comment by abhinaba-ghosh** [comment]
Hi @MJavedAli ,

The framework has been enhanced. Now you can provide the reporting locations from `.env` file:

```ssh
#report directory
TEST_REPORT_DIRECTORY=target
SERENITY_REPORT_DIRECTORY=target/site/serenity
```
`TEST_REPORT_DIRECTORY` for storing all logs related to cucumber son, test logs, accessibility reports etc

`SERENITY_REPORT_DIRECTORY` for storing only serenity reports. 

Let us know if that works for you.

**Comment by abhinaba-ghosh** [comment]
If you want to change the features folder, you need to change below codes:

```js
specs: [`${process.cwd()}/e2e/features/**/*.feature`],

  serenity: {
    runner: 'cucumber',
    requirementsDirectory: `${process.cwd()}/e2e/features`,
```

**Comment by MJavedAli** [comment]
Hi @abhinaba-ghosh , I tried the above steps in config file , but no luck - see my snippets and folder structure below - 
![image](https://user-images.githubusercontent.com/30997178/88164805-42d66780-cc32-11ea-96fe-20abc0dc0996.png)

folder structure :- 
![image](https://user-images.githubusercontent.com/30997178/88164847-571a6480-cc32-11ea-9d08-fb3053dc7b2a.png)

**Comment by MJavedAli** [comment]
I am able to generate report after overriding  the feature path in serenity cli - lib :

 serenity-bdd run --cacheDir ./lib/serenity-cli --features target/site/serenity
